### ISSUE TITLE
Pull SB Admin 2 dependencies out of Userfrosting core

### ISSUE THREAD

**Issue by odoell** [userfrosting/UserFrosting#526] opened 2016-03-25 00:24 UTC
Hi,

now after working this week with Userfrosting and the underlying theming feature, i like the core system of managing users, groups, routing...

But it would be awful when the theme dependencies of the SB Admin 2 Bootstrap theme (css and js) would be pulled out of Userfrosting core files, i.e. initialize.php. When someone wants to not only modify the templates based on SB Admin 2 rather use a complete different Theme or complete own written theme. The registering of css and js must be monkey patched, so the site is not crowded with unused css and js files.

Making it difficult to update to future releases.
The plugin approach would be some starting point to integrate different css and js files. Functions and hooks for including such files later, are already available.

A default theme based on SB Admin 2 still can exist, maybe also there could be some sort of inheritance chain implemented, like the child themes in drupal. So not every theme must integrate configuration of css and js files. For example, when you just have to change or add new templates.

Greetings Oliver

**Comment by alexweissman** [comment] 2016-03-25 00:56
We're working on it.  Asset management in general for UF is kind of jacked.  The problem is that in addition to the theming constraint, we also have the asset compilation constraint (i.e., it needs to be possible to generate minified/concatenated/whatever asset files for each theme).  

We're looking into making all of this work with a combination of [Gulp](https://github.com/dowjones/gulp-bundle-assets/) and [streams](https://github.com/userfrosting/UserFrosting/issues/512).

If you want to contribute to the conversation about this general problem, I'd strongly encourage you to join us in [chat](https://gitter.im/userfrosting/UserFrosting) as I have been talking about it for some time now.

**Comment by odoell** [comment] 2016-03-26 01:42
As a frontend dev i welcome the idea of a gulp / grunt / npm workflow, For example also pulling out minifying files out of the server. In my opinion, we are not talking about some unexperienced user when it comes to developing some complete new theme, no matter for what kind of backend system.

but for now i do not really see the advantage of working with streams with somehow static assets as css or js files. We just want to deliver the appropriate files to the client, why not use the program its use was made for, the webserver. If we want to change the contents of our css or js dynamically, than the use of streams may be useful.

Whats about making some proposal for handling themes and plugins absolutely the same way. As plugins and themes are the same. Plugins extend the system with functionality, themes extend with rendering the view.

Whats about using some config files for plugins and themes, so i could configure my used js libraries in a yaml file for example and the core system implements them as configured... for example...

**Comment by alexweissman** [comment] 2016-03-26 04:01
The cool thing about streams is that it lets us abstract away the various locations of assets, templates, etc - that would be inevitable with themes and plugins - so they can be generically handled by the core code.  

The problem with having raw assets served directly by the webserver, is that the webserver needs to find the appropriate file, and then it needs to be in the public document root.  If we serve raw assets through the routing system, it will be easier to separate "public" and "private" files - however it will also be somewhat slower.  For production-ready, compiled assets, I absolutely agree - these can be written to the public directory by Gulp, and then served directly.

Definitely agree with you about treating themes as a type of plugin.  This is exactly what [Grav](http://learn.getgrav.org/basics/what-is-grav), a project I admire very much, does.

I also agree with you about separating out config info into either YAML or separate PHP files.  Grav and Laravel both have useful `Config` classes, which we could use.  I'm also thinking about moving to Slim 3, which does a better job separating out the configuration from the application.

Again, this is best discussed in chat.  It sounds like we are very much on the same page about the future of UF, so I'd definitely like to chat with you about this in real-time.

**Comment by r3wt** [comment] 2016-03-29 06:00
1 more vote for gulp

**Comment by alexweissman** [comment] 2016-06-01 23:30
I'm gonna reference #504 and #512 here.

**Comment by alexweissman** [comment] 2016-06-01 23:40
Also, #486.

**Comment by alexweissman** [comment] 2016-11-05 01:22
This is now solved via the Sprinkle system in v4.  Assets are served through the Slim application during development, via the `/assets-raw/` route.  However, after compiling the assets using Gulp, they can be served directly by the webserver for faster performance.

**Closed by alexweissman** 2016-11-05 01:22 UTC
Labels: long-range planning, standards and best practices
