### ISSUE TITLE
Uf modal causes error when closed

### ISSUE THREAD

**Issue by abdullahseba** [userfrosting/UserFrosting#732] opened 2017-06-07 21:53 UTC
Uf form causes an error when closed which stops any other modal been opened.
![image](https://user-images.githubusercontent.com/25548754/26903220-558b9634-4bd4-11e7-8be6-fb7dc800957c.png)

**Comment by alexweissman** [comment] 2017-06-07 23:20
I have been able to replicate this error in the current release of UF 4.0.  @Silic0nS0ldier, is it possible that this is related to the recent overhaul of `ufModal` that you did?

**Comment by Silic0nS0ldier** [comment] 2017-06-08 02:12
Confirmed that this issue has occurred after the overhaul, investigating fix now.

**Comment by Silic0nS0ldier** [comment] 2017-06-08 03:13
Cause isolated to unbinding of events. Despite code identical, it seems to behave differently. Scoping event removal to modal itself (of which the events are attached to), seems to resolve the original issue.

Interestingly, switching between the roles modal and change password modal seems to be generating errors. (at an exponential rate when switching between them) The exact cause is unknown.
![image](https://user-images.githubusercontent.com/17376090/26910305-4cd1b738-4c49-11e7-8bd0-41c053af6390.png)

**Comment by Silic0nS0ldier** [comment] 2017-06-08 06:04
I did not close this a hour ago. -_- What are you doing GitHub!

**Comment by alexweissman** [comment] 2017-06-09 21:47
Please note, this is only an issue in UF 4.1 with the new `ufTable` plugin architecture.

**Comment by alexweissman** [comment] 2017-06-15 17:50
So, is this still an issue?

**Comment by abdullahseba** [comment] 2017-06-15 17:52
you tell me!

**Comment by alexweissman** [comment] 2017-06-15 17:53
Well it looks like it was fixed in [this commit](https://github.com/userfrosting/UserFrosting/commit/8709ae5335cf934ac7aaacd80185838c7e723653), but then @Silic0nS0ldier reopened the issue?

**Comment by abdullahseba** [comment] 2017-06-15 17:55
Well he said he dint close it in the first place...

**Comment by alexweissman** [comment] 2017-06-18 22:39
It would appear that for now we have reverted to the old style of the plugin?  I have opened a new issue for this: https://github.com/userfrosting/UserFrosting/issues/740

**Closed by alexweissman** 2017-06-18 22:39 UTC
Labels: confirmed bug, frontend
