### ISSUE TITLE
FeatureRequest: Hide locale select from UI if only one locale is available

### ISSUE THREAD

**Issue by avsdev-cw** [userfrosting/UserFrosting#968] opened 2019-04-16 12:07 UTC
It would be handy if the locale select/display could be removed via a setting or if the system could detect when there is only 1 locale available and default to hiding the option to change it etc in that instance.

**Comment by lcharette** [comment] 2019-04-16 12:51
Kind of a duplicate of https://github.com/userfrosting/UserFrosting/issues/850

Unwanted locale can already be disabled in the config file. See https://learn.userfrosting.com/advanced/i18n#setting-up-the-site-language

I do like the idea of hiding the select if only one locale exist thought. But I'm not sure how complex it would be compare to the benefit of it considering the use of schema and default value...

**Comment by avsdev-cw** [comment] 2019-04-16 13:11
It kinda is, we already disable all locales bar en_US.

From our point of view its more of a "if the user doesn't need to use it, they don't need to know it exists" sorta thing.

I have started looking at it myself, but using overrides in another sprinkle. Once I started getting into the depths of it I quite quickly realised that actually there was some work needed in the UF default install. In some place the locale is hidden by a role, but others there is no wrap around it at all so there is a bit of inconsistency there already.

**Comment by lcharette** [comment] 2019-04-16 13:18
The admin UI controller has a `hidden` property. Same logic could be used in the normal user setting page controller. Locale field could then be added directly to this hidden array if the number of non null locale is less than 2.

**Comment by avsdev-cw** [comment] 2019-04-16 13:20
That's what I was thinking. I'll have to pull a new dev copy down and submit a PR if I get half a chance to look at it again.

**Comment by lcharette** [comment] 2019-04-19 00:20
Merged in hotfix for 4.2.1 release.

**Closed by lcharette** 2019-04-19 00:20 UTC
Labels: core feature request, internationalization, up-for-grabs, user experience
