### ISSUE TITLE
Unable to Create Master Account, config_token issue?

### ISSUE THREAD

**Issue by Sperko** [userfrosting/UserFrosting#518] opened 2016-02-17 00:51 UTC
Hello

I have set up the database and the installation seems to be ok but when I try to create the master account when I input the config_token from uf_configuration and click register it just loads/spins then nothing happens

I have tried this on 3 separate installs with different database names but the issue is still there

Also, is there any way I can bypass this step to create the master account?

Thank you!

**Comment by alexweissman** [comment] 2016-02-17 02:09
Like I said in chat, you need to check your PHP error log, and browser console for any error messages before we can help you.  Saying that it "loads/spins and nothing happens" is far too generic, and there is no way we can troubleshoot without more information.

**Comment by Sperko** [comment] 2016-02-17 10:51
Sorry for not making it clearer, the spinning animation on the register button is what I was referring to, it appears to try and load something but it failed to proceed to the next step and stays on the register page

The only changes I had to make was adding the RewriteBase /project/public/ line (renaming to /abc/public/ - abc being the project directory) to .htaccess because I got a 404 error

I have a few questions if you can answer them please:

I was unable to find the php error log, can you help me find this?

I have used the same database information for both production and development in userfrosting/config-userfrosting.php, is this correct?

When I  get the config_token from uf_configuration I just copy and paste it into the register page, am I doing this correct too?

Thanks for replying!

**Comment by malle-pietje** [comment] 2016-02-17 13:26
PHP error log depends on your web server. Which are you using? You could also quickly create page somewhere on the web server like so:
```php
<?php
phpinfo();
?>
```
and then access this page from your browser. In all the info there will also be information on how your error log is configured.

**Comment by Sperko** [comment] 2016-02-17 14:55
I'm using a host so I'm not sure which web server it is

I have enabled display_errors in php and have tried the code you suggested but I'm getting 403 forbidden error, I will ask my host where the error log is located to see if there are any errors

**Comment by malle-pietje** [comment] 2016-02-17 15:00
that doesn't sound good. Better check with your hosting provider.

**Comment by Sperko** [comment] 2016-02-17 15:04
I have looked around and found error_log in the public folder within the project directory, there is a lot of info in this file so I'm not sure if this is the correct info or file you need, is there anything specific you need from it? 

Thanks for responding :+1:

**Comment by Netrilix** [comment] 2016-02-17 15:16
Generally you'd want to grab the last lines with the same timestamp, so if the last error (at the bottom of the file) occurred at 18:21:40, copy all the errors from 18:21 (if there aren't too many) or just 18:21:40 (if there are a lot) at the end of the file.

**Comment by Sperko** [comment] 2016-02-17 15:49
Good idea, I cleared our the error_log and reset the database and tried registering the master account, this is the complete error_log

`[17-Feb-2016 10:46:00 America/New_York] The configuration table could not be loaded.  Falling back to default configuration settings.
[17-Feb-2016 10:46:00 America/New_York] The configuration table could not be loaded.  Falling back to default configuration settings.
[17-Feb-2016 10:46:00 America/New_York] Checking php version
[17-Feb-2016 10:46:00 America/New_York] Checking db connection
[17-Feb-2016 10:46:00 America/New_York] Checking any current tables
[17-Feb-2016 10:46:00 America/New_York] Done with checks
[17-Feb-2016 10:46:00 America/New_York] Installing`

**Comment by Sperko** [comment] 2016-03-01 21:30
I'm going to attempt the installation again tomorrow and if I have the same problem I will speak to my host to see if there's anything on their end they can do

**Comment by Sperko** [comment] 2016-03-02 19:18
Still not working is there any way I can bypass the config_token verification to create the master account, this seems to be the only step that doesn't work for me

thank you

**Comment by alexweissman** [comment] 2016-03-02 19:26
You could comment out the code that checks the token, but chances are if that isn't working, you'll have problems beyond that step as well.  

The messages in your error log look normal to me (right now, we do all logging to the error log, unfortunately even "successful" messages). 

Maybe the problem is on the client side.  Are you getting any errors in your browser console?  What does the POST request look like when you press the "create master account" button?

**Comment by Sperko** [comment] 2016-03-19 03:19
Unfortunately I cannot get it to work but I really wanted to test this system out!

In future versions maybe you can add a config option to bypass the security check and register the master account without the need for the config_token, something that I could of tried as I'm sure my problem is directly related to that

Anyway,
Thanks for the help!

**Comment by alexweissman** [comment] 2016-03-19 16:07
Like I said, you can bypass the config token check by removing a few lines from the installer: https://github.com/userfrosting/UserFrosting/blob/master/userfrosting/controllers/InstallController.php#L189-L193.

But again, I highly doubt that is the problem.  You mentioned that you're using a `RewriteBase /project/public/` directive.  Can you remove that, and simply access your site at `http://localhost/project/public` instead?

**Comment by Sperko** [comment] 2016-04-07 23:58
I am sorry for the slow reply here I've been working on a few projects

I tried removing the code from the InstallController.php but I still get the original problem

And if I remove the RewriteBase I get a 404 error at /project/public

I will try 1 more time for luck

**Comment by Sperko** [comment] 2016-04-08 00:23
Hmm still not working

I created a gif so you can see what happens https://gyazo.com/f15157fd53436dd377df8b9a0331aa15

Using a fresh installation I removed the token code from InstallController.php before setting up the database info and then went to /project/public WITHOUT adding the RewriteBase in the .htaccess

I still get a 404 error at /project/public but when I clicked "click here to return to the front page" it took me to myhost/home/myaccount/public_html/uf/public/install - and the page loaded, which I attempted to register master account with, but I get the same result as before

**Comment by alexweissman** [comment] 2016-04-08 01:12
At this point, I would consider trying to get some more help in chat.

**Comment by Sperko** [comment] 2016-04-08 17:23
Thanks I will try that!

**Comment by alexweissman** [comment] 2016-04-10 00:56
Closing this, as it is a highly specific issue that we are now discussing in chat.

**Closed by alexweissman** 2016-04-10 00:56 UTC
Labels: troubleshooting
