### ISSUE TITLE
NPM dependency installation error

### ISSUE THREAD

**Issue by denispiovarci** [userfrosting/UserFrosting#1049] opened 2019-11-05 15:11 UTC
Hi, first time installing UserFrosting on Windows via Bash. I followed instructions in Installation thread on the official web site. I use Vagrant/Homestead. After running `vagrant up`, i got an error on new created site which looks like this:
<img width="925" alt="weberr" src="https://user-images.githubusercontent.com/32193992/68219376-2e8c0500-ffe6-11e9-8339-a9d4be94b938.png">

Then i followed `vagrant ssh` command, then `php bakery bake`. This error showed up.
<img width="470" alt="npm err" src="https://user-images.githubusercontent.com/32193992/68219473-5713ff00-ffe6-11e9-8ee1-b6d90972d571.png">

As i read forums and stacks, i discovered it is Windows problem with symbolic links. I tried to install acorn with `--no-bin-links`, and installation was successfull. Although i run the `php bakery bake` command again and the error still showed up. Do you have any suggestions what could be the solution to this type of error? All help is welcomed. Thank you!

**Comment by lcharette** [comment] 2019-11-05 15:21
Possibly related to #1046

**Comment by lcharette** [comment] 2019-11-05 15:22
Possible duplicate of #961 also

**Comment by denispiovarci** [comment] 2019-11-05 15:42
Solved it with https://github.com/userfrosting/UserFrosting/issues/961#issuecomment-516661612

**Closed** 2019-11-05 15:59 UTC
Labels: possible bug
