### ISSUE TITLE
Site cache reset upon login

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/UserFrosting#828] opened 2017-12-13 08:50 UTC
To replicate:

1. Have UF setup in production mode with account sprinkle used.
2. Login with the file systems permission check tricked into succeeding (so that the pass state is in the cache) once, by placing `$this->cache->forever('checkEnvironment', 'pass');` just after line 69 of `CheckEnvironment.php`. Revert once logged in.
3. Logout and log back in, or just login with a different session (different browser, cleared browser cache, private mode, etc).
4. Be faced with warning page.

The problem:

Aside from not working as expected, this means that UF is checking file system permissions (and more) much more frequently than expected. The performance hit here is minimal, but worth mentioning. If the cache gets used elsewhere (userland or in UF itself), then issues and potentially much more substantial performance issues might arise.

Since the cache is expected to... well... cache, this should probably be fixed.

(first observed in develop branch, unknown if hotfix and master impacted)

**Comment by lcharette** [comment] 2017-12-13 18:55
Not sure I understand. Is it an issue with caching, or `CheckEnvironment` ? 

What cache driver are you using? File cache driver is bad, but essential for dev env. You could try Memcache or Redis to see if you can replicate.

**Comment by Silic0nS0ldier** [comment] 2017-12-13 21:30
`CheckEnvironment` sets a forever entry in the cache on success. This cache entry determines if anything should be done. Physically looking in the cache folder before and after login, it gets emptied. Can also see the entry in the cache files, which confirms that this is indeed the correct location.

**Comment by lcharette** [comment] 2017-12-13 21:33
That's bad. I'll try to replicate... Can you test it does the same thing for different cache "key" and cache provider?

**Comment by Silic0nS0ldier** [comment] 2017-12-13 21:55
Could this be down to changes introduced by  #649?

**Comment by Silic0nS0ldier** [comment] 2017-12-13 21:58
For the sake of having everything in one place, I tracked down what is physically emptying the cache on login/logout.
https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/account/src/Authenticate/Authenticator.php#L196
https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/account/src/Authenticate/Authenticator.php#L254

**Comment by lcharette** [comment] 2017-12-14 04:22
Indeed, #649 introduced global, user and session cache. Session cache is used for the alert system and should be cleared on logout. Maybe there's a mixup between the types of cache.

Did you try with Redis/Memcache? Could be the File implementation acting up ? The file tags are custom stuff...

**Comment by Silic0nS0ldier** [comment] 2017-12-14 04:24
Haven't had the cache yet. (mainly cause I'll have to figure out how to get both running first)

**Comment by Silic0nS0ldier** [comment] 2017-12-14 11:51
Issue can be replicated while using Redis.

**Comment by alexweissman** [comment] 2017-12-20 16:18
Is the problem purely caused by `CheckEnvironment`?  If so, resolving #630 could also solve this problem.

**Comment by Silic0nS0ldier** [comment] 2017-12-21 01:00
No, I don't think this is caused by `CheckEnvironment`. (unless its storing the pass result in the wrong cache) Best I can tell, the login/logout code clears the site cache, instead of whatever it is supposed to. (the current session cache I suppose)

**Comment by lcharette** [comment] 2017-12-21 01:41
I replicated the issue. It's not related to `CheckEnvironment`...

**Comment by lcharette** [comment] 2017-12-21 02:39
Bad tags where bad. Fixed in `hotfix`.

**Closed** 2017-12-21 02:39 UTC
Labels: possible bug
