### ISSUE TITLE
Create User Without SMTP

### ISSUE THREAD

**Issue by pauljcurtis** [userfrosting/UserFrosting#776] opened 2017-07-28 17:50 UTC
For development could a user be created without the requirement for SMTP settings. Could the 'email' go to logs instead?

**Comment by alexweissman** [comment] 2017-07-28 17:58
I think we could consider a general switch that shunts all mail to a log file instead, during development.

**Comment by lcharette** [comment] 2018-03-29 13:27
Would make the Vagrant install perfect... It's the only thing *not* set automatically in #829

**Comment by lcharette** [comment] 2018-10-28 20:45
Duplicate of #763.

**Closed by lcharette** 2018-10-28 20:45 UTC
Labels: core feature request
